### ISSUE TITLE
Python packages with dash - are not removable

### ISSUE THREAD

**Issue by kunitoki** [juancarlospaco/plz#11]
```
$ python -m pip install break-my-python
Collecting break-my-python
  Downloading break_my_python-0.0.2-py2.py3-none-any.whl (4.4 kB)
Installing collected packages: break-my-python
Successfully installed break-my-python-0.0.2

$ plz uninstall break-my-python
Uninstall 1 Packages:	@["break-my-python"]

$ ls -l lib/python3.10/site-packages/
__pycache__
_distutils_hack
break_my_python-0.0.2.dist-info
break_my_python.pth
break_my_python.py
distutils-precedence.pth
pip
pip-22.2.2.dist-info
pkg_resources
setuptools
setuptools-65.4.1.dist-info
```

**Comment by kunitoki** [comment]
we should probably return an error code rather than 0 if we try to uninstall a package and we encounter no files to remove

**Comment by juancarlospaco** [comment]
That package looks weird,  ...almost like malware, 
I would focus on frequently installed packages first.

**Comment by Kd-Here** [comment]
Hey @juancarlospaco can I help you with that.
It will really help me to understand actual cli working of python.

> probably return an error code rather than 0 if we try to uninstall a package and we encounter no files to remove
Is the task right.

**Comment by juancarlospaco** [comment]
Pull Requests are very welcome and will be merged...

**Comment by kunitoki** [comment]
That package is just to be able to test a package breaking python. Isn't one of the selling point of `plz` that it will `work even if pip or virtualenv is broken`.

Just take a package with dash in the name
