### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by agucova** [juancarlospaco/plz#2]
Weird question, why does GitHub insist this project is 100% Python when it's 100% Nim? I only found one python file and it's empty. (`/plz.py`)

Maybe you should remove the "100% Python" badge on the README? I thought it was written in pure Python until I read that there is no garbage collector.

**Comment by juancarlospaco** [comment]
Python is made from C, C++, Fortran, Cython, etc. CPython is named because is written in C. :shrug:

**Comment by agucova** [comment]
What? I'm not sure how that's relevant. A bunch of languages aren't self-contained and yet their programs can be described as "pure" if they don't outsource functionality. However, I don't see how this has anything to do with how GitHub classifies files.

**Comment by juancarlospaco** [comment]
Nim for Python, is just like Cython for Python.

It wont need garbage collector, because it uses Rust like memory management.

Nim has Python syntax, but I am not using it right now.

I find Nim searching for Cython alternatives that run on the browser.

I agree this issue is not relevant.

**Comment by agucova** [comment]
Creo que no me expresé bien jajajaja

Lo que quiero decir es que a pesar de que la herramienta sirve para Python, **no está escrita para Python**. De la misma forma, CPython está escrito en C, no Python. 

Por alguna razón GitHub cree que plz está escrito en Python, e incluso "niega" la existencia de Nim en el proyecto. Me imagino que eso es porque Nim no está siendo detectado, y habiendo un archivo .py (aunque vacío), GitHub asume que todo es Python.

El language tag de GitHub indica en que lenguaje(s) fue escrito un repositorio, si funcionara correctamente, debería decir 100% Nim, ya que no hay código de Python en tu repositorio. Mi recomendación era quitar el badge opcional que hay en el README, dado que solo muestra un error de parte de GitHub.

**Comment by juancarlospaco** [comment]
Cython is considered Python, therefore Nim is Python. :shrug:

**Comment by agucova** [comment]
But... Cython is written on C and Python, Nim is just written on Nim. (The compiler is pure Nim). Cython is an extension to Python, and Nim is well, just Nim.

Cython as a language is a superset of Python, written mostly on C, with the ability to use C and Python seamlessly. It compiles to Python modules. You could probably call it Python because at its base, it follows the Python specs and it's considered an extension of the Python language.
 
Nim is written on Nim, compiles to JS and C (as well as other targets) and simply has a "Python-like syntax", it never implements the Python specification and it has some profound differences with Python (like typing, the fact that Nim is compiled, speed, metaprogramming abilities). Nim is **not Python**, even though it may look like it.

**Comment by juancarlospaco** [comment]
Nim also has the ability to use C and Python seamlessly. It compiles to Python modules.
Has Python syntax that you can import. You can even write it like PEP8, but I am not using it right now.

**Comment by agucova** [comment]
Yeah, but that's not the point. You can technically use almost any programming language with Nim (tho it may get difficult), but that doesn't mean all languages are the same.

**Comment by agucova** [comment]
A language is much more than its syntax, this is true for programming and any language in general. Spanish has a syntax, but it also has a vocabulary, a grammar, semantics and culture behind it.

Python is not a just a way of writing code, it's not a coding style. It's a formally specified programming language with more than 800+ Enhancement Proposals, a bunch of which make up part of the language.

Python is also a community, a package ecosystem, a standard library, a culture...

Nim can run almost every other language indirectly, so can Python and Bash and almost every modern programming language. Being able to call another language is not being that language. Having a similar syntax isn't either. And in terms of functionality, you're most definitely not following the Duck Rule:

> "If it looks like a duck, swims like a duck, and quacks like a duck, then it probably is a duck"

Except this duck only looks like a duck; it swims like C and it quacks like Ada!

**Comment by juancarlospaco** [comment]
So, go to Django and Flask and say thats not Python because they use JavaScript too.
Go to Pandas and Pytorch and say thats not Python because they use Cython, C++ too.
Go to CPython and CTypes projects and say thats not Python because they use C too.
:shrug:

**Comment by agucova** [comment]
Django and Flask are written almost completely in Python. They are (for the most part) python. They certainly use JavaScript, but that's up to you, not the library. They're also Python libraries, but they're not "Python", that's semantically incorrect, they're most certainly not equal to Python. Python is a language, not a library.

Pandas and Pytorch optimize their speed by using C implementations, you could properly say Pandas are Pytorch are Python libraries written in C and Python. in the same way that you can write Python libraries in Nim. They're again, Python libraries written partly in another language.

CPython and CTypes most certainly are written C, they're not Python, they're Python implementations, there's a difference. Nim is written on Nim, but that's actually one of the oddities of the language, the fact that it's self-contained.

**Comment by juancarlospaco** [comment]
I agree is out of hand, and not really relevant as you said.

It will be uploaded to PYPI some day, works and is maintained.

**Comment by agucova** [comment]
I said that it's not relevant that Python is written in C, not that my issue was not relevant. But yeah :rofl:
